CREATE DATABASE LABORATOIRE;

USE  LABORATOIRE;
 
CREATE TABLE TEST_RESULT(
  ID INT NOT NULL AUTO_INCREMENT,
  ID_TEST_REQUEST INT NOT NULL,
  NAME_TR VARCHAR(50) NOT NULL,
  VALUE_TR VARCHAR(20),
  PRIMARY KEY (ID)
);                                               

CREATE TABLE TEST_REQUEST(
  ID INT AUTO NOT NULL,
  ID_PARTIENT INT AUTO NOT NULL,
  ID_TEST INT AUTO NOT NULL,
  ID_BILL INT AUTO NOT NULL,
  NAME_TREQ VARCHAR(50) NOT NULL,
  DATE_TREQ Date(8),
  STATUT_TREQ VARCHAR(255)
);

    
  CREATE TABLE PATIENT(
   ID_PATIENT INT AUTO primary key,
   LAST_NAME VARCHAR(25) NOT NULL,       
   FiRST_NAME VARCHAR(25),                                                  
    ADRESS VARCHAR(50),
    BOTH_DATE Date(8),
    PHONE_NIMBER integer(20),                                                    
    SEX VARCHAR(1));

  

  CREATE TABLE BILL(
   ID_BILL INT AUTO primary key,
                                                              
   CREATION_DATE Date(8),
   TOTAL_AMOUNT INT,
   TOTAL_AMOUNT_PAID INT);

 CREATE TABLE TEST(
  ID_TEST INT AUTO NOT NULL,
                                                           
  ID_TEST_TYPE INT AUTO NOT NULL,
  NAME_T VARCHAR((25)) NOT NULL,
  DESCRIPTION_T VARCHAR(255),
  PRICE_T  INT,
  MIN_TIME_FRAME integer(100),
  MAX_TIME_FRAME integer(100));
 
 CREATE TABLE TEST_TYPE(

  ID_TEST_TYPE INT AUTO primary key ,
  NAME_TP VARCHAR(50));

 CREATE TABLE RESULT(
  ID_RESULT INT AUTO  NOT NULL  ,
  ID_TEST INT AUTO NOT NULL,
  NAME_R VARCHAR(25),
  DESCRIPTION_R VARCHAR(255));

 CREATE TABLE RESULT_ITEM(
  ID_RESULT_ITEM INT AUTO NOT NULL ,
  ID_RESULT INT AUTO NOT NULL ,
  UNIT VARCHAR(25),
  TYPE_RI VARCHAR(255));                                                
                                                                              

 CREATE TABLE BILL_ITEM(
  ID_BILL_ITEM integer(25) AUTO NOT NULL,         
  ID_BILL integer(20) AUTO NOT NULL,
  PRICE INT,
  QUANTITY integer(55),
  DISCOUNT integer(50),
  DESCRIPTION_B VARCHAR(255));

 CREATE TABLE ROLE(
  ID_ROLE integer(50) AUTO primary key,    
  NAME_R VARCHAR(25),
  DESCRIPTION_RO VARCHAR(255));

 CREATE TABLE USER_ROLE(
  ID_ROLE INT AUTO NOT NULL,
  ID_USER integer(200) AUTO NOT NULL);

 CREATE TABLE USER(
  ID_USER integer(45) AUTO primary key,
  NAME_T VARCHAR(20) NOT NULL,
 FIRST_NAME VARCHAR(25),
  ADRESS VARCHAR(20),
  PHONE_NUNBER integer(60),
  PASSWORD_U VARCHAR(50) NOT NULL);

 CREATE TABLE PAYMENT(
  ID_PAYMENT INT AUTO NOT NULL,
  ID_USER INT AUTO NOT NULL,
  ID_BILL INT AUTO NOT NULL,
  DATE_PY Date(8),
  AMOUNT_PY integer(55));

 CREATE TABLE SAMPLE(
  ID_SAMPLE integer(20) AUTO NOT NULL,
  ID_SAMPLE_TYPE integer(40) AUTO NOT NULL,
  ID_TEST_REQUEST integer(50) AUTO NOT NULL,
  NAME_S VARCHAR(255) NOT NULL,
  PRODUCTION_DATE Date(8),
  EXPIRATION_DATE Date(8));

 CREATE TABLE SAMPLE_TYPE(
  ID_SAMPLE_TYPE INT AUTO primary key,
  NAME_ST VARCHAR(255),
  DESCRIPTION VARCHAR);

-- Foreign keys definition
-- ***********************
ALTER TABLE TEST_RESULT ADD CONSTRAINT FK_TEST_REQUEST FOREIGN KEY (ID_TEST_REQUEST) REFERENCES TEST_REQUEST(ID);
 
ALTER TABLE USER_ROLE ADD CONSTRAINT PK_USER_ROLE PRIMARY KEY (ID_ROLE, ID_USER);
ALTER TABLE TEST_REQUEST ADD CONSTRAINT FK_TEST_REQUEST FOREIGN KEY (ID_PATIENT, ID_BILL, ID_TEST) REFERENCES PATIENT, BILL, TEST (ID_TEST_RESULT, ID_BILL, ID_TEST);
ALTER TABLE TEST ADD CONSTRAINT FK_TEST FORENGN KEY (ID_TEST_TYPE) REFERENCES TEST_TYPE (ID_TEST_TYPE);
ALTER TABLE RESULT ADD CONSTRAINT FK_RESULT FOREIGN KEY (ID_TEST) REFERENCES TEST (ID_TEST);
ALTER TABLE RESULT_ITEM CONSTRAINT FK_RESULT_ITEM FOREIGN KEY (ID_RESULT) REFERENCES RESULT (ID_RESULT);
ALTER TABLE BILL_ITEM CONSTRAINT FK_BILL_ITEM FOREIGN KEY (ID_BILL) REFERENCES BILL (ID_BILL);
ALTER TABLE PAYMENTS CONSTRAINT FK_PAYMENTS FOREIGN KEY (ID_USER, ID_BILL) REFERENCES USER, BILL (ID_USER, ID_BILL);
ALTER TABLE SAMPLE  CONSTRAINT FK_SAMPLE FORIEGN KEY (ID_SAMPLE_TYPE, ID_TEST_REQUEST) REFERENCES SAMPLE_TYPE, TEST_REQUEST (ID_SAMPE_TYPE, ID_TEST_REQUEST);