CREATE DATABASE LABORATOIRE;

USE  LABORATOIRE;
 
CREATE TABLE TEST_RESULT(
  ID INT NOT NULL AUTO_INCREMENT,
  ID_TEST_REQUEST INT NOT NULL,
  NAME_TR VARCHAR(50) NOT NULL,
  VALUE_TR VARCHAR(20),
  PRIMARY KEY (ID)
);                                               

CREATE TABLE TEST_REQUEST(
  ID INT NOT NULL AUTO_INCREMENT, 
  ID_PATIENT INT NOT NULL,
  ID_TEST INT NOT NULL,
  ID_BILL INT NOT NULL,
  NAME_TREQ VARCHAR(50) NOT NULL,
  DATE_TREQ DATE NULL,
  STATUT_TREQ VARCHAR(100) NULL,
  PRIMARY KEY (ID)
);
    
Create table PATIENT(
  ID INT NOT NULL AUTO_INCREMENT, 
  LAST_NAME VARCHAR(25) NOT NULL,       
  FiRST_NAME VARCHAR(25) NULL,                                                  
  ADRESS VARCHAR(50) NULL,
  BOTH_DATE DATE NULL,
  PHONE_NUMBER INT NULL,                                                    
  SEX VARCHAR(1) NULL,
  PRIMARY KEY (ID)
);
  
CREATE TABLE BILL(
  ID INT NOT NULL AUTO_INCREMENT, 
  CREATION_DATE DATE NULL,
  TOTAL_AMOUNT INT NULL,
  TOTAL_AMOUNT_PAID INT NULL,
  PRIMARY KEY (ID)
);
Create table TEST(
  ID INT NOT NULL AUTO_INCREMENT,
  ID_TEST_TYPE INT NOT NULL,
  NAME_T VARCHAR(25) NOT NULL,
  DESCRIPTION_T VARCHAR(255) NULL,
  PRICE_T INT NULL,
  MIN_TIME_FRAME INT NULL,
  MAX_TIME_FRAME INT NULL,
  PRIMARY KEY (ID)
);  
CREATE TABLE TEST_TYPE(
  ID INT NOT NULL AUTO_INCREMENT, 
  NAME_TT VARCHAR(50) NULL,
  PRIMARY KEY (ID)
);
 CREATE TABLE RESULT(
  ID INT NOT NULL AUTO_INCREMENT,
  ID_TEST INT NOT NULL,
  NAME_R VARCHAR(25) NULL,
  DESCRIPTION_R VARCHAR(255) NULL,
  PRIMARY KEY (ID)
);
CREATE TABLE RESULT_ITEM(
  ID INT NOT NULL AUTO_INCREMENT,
  ID_RESULT INT NOT NULL,
  UNIT VARCHAR(25) NULL,
  TYPE_R VARCHAR(255) NULL,
  PRIMARY KEY (ID)                                                
);                                                                              
CREATE TABLE BILL_ITEM(
  ID INT NOT NULL AUTO_INCREMENT,         
  ID_BILL INT NOT NULL,
  PRICE INT NULL,
  QUANTITY INT NULL,
  DISCOUNT INT NULL,
  DESCRIPTION_B VARCHAR(255) NULL,
  PRIMARY KEY (ID)
);
CREATE TABLE ROLE(
  ID INT NOT NULL AUTO_INCREMENT,    
  NAME_R VARCHAR(25) NULL,
  DESCRIPTION_R VARCHAR(255) NULL,
  PRIMARY KEY (ID) 
);
CREATE TABLE USER(
  ID INT NOT NULL AUTO_INCREMENT,
  LAST_NAME VARCHAR(20) NOT NULL,
  FIRST_NAME VARCHAR(25) NULL,
  ADRESS VARCHAR(20) NULL,
  PHONE_NUNBER INT NULL,
  PASSWORD_U VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID)
);
CREATE TABLE USER_ROLE(
  ID_USER INT NOT NULL,
  ID_ROLE INT  NOT NULL,
  PRIMARY key(ID_USER, ID_ROLE)
);
CREATE TABLE PAYMENTS(
  ID INT NOT NULL AUTO_INCREMENT,
  ID_USER INT NOT NULL,
  ID_BILL INT NOT NULL,
  DATE_P DATE NULL,
  AMOUNT_P INT NULL,
  PRIMARY KEY (ID)
);
CREATE TABLE SAMPLE(
  ID INT NOT NULL AUTO_INCREMENT,
  ID_SAMPLE_TYPE INT NOT NULL,
  ID_TEST_REQUEST INT NOT NULL,
  NAME_S VARCHAR(255) NOT NULL,
  PRODUCTION_DATE DATE NULL,
  EXPIRATION_DATE DATE NULL,
  PRIMARY KEY (ID)
);
CREATE TABLE SAMPLE_TYPE(
  ID INT NOT NULL AUTO_INCREMENT,
  NAME_ST VARCHAR(255) NULL,
  DESCRIPTION VARCHAR(255) NULL,
  PRIMARY KEY (ID)
);
-- Foreign keys definition
-- ***********************
ALTER TABLE TEST_RESULT ADD CONSTRAINT FK_TEST_REQUEST FOREIGN KEY (ID_TEST_REQUEST) REFERENCES TEST_REQUEST(ID);
 

ALTER TABLE TEST_REQUEST ADD CONSTRAINT FK_PATIENT FOREIGN KEY (ID_PATIENT) REFERENCES PATIENT(ID);
ALTER TABLE TEST_REQUEST ADD CONSTRAINT FK_BILL FOREIGN KEY (ID_BILL) REFERENCES BILL(ID);
ALTER TABLE TEST_REQUEST ADD CONSTRAINT FK_TEST FOREIGN KEY (ID_TEST) REFERENCES TEST(ID);
ALTER TABLE TEST ADD CONSTRAINT FK_TEST_TYPE FOREIGN KEY (ID_TEST_TYPE) REFERENCES TEST_TYPE(ID);
ALTER TABLE RESULT ADD CONSTRAINT FK_TEST_RESULT FOREIGN KEY (ID_TEST) REFERENCES TEST (ID);
ALTER TABLE RESULT_ITEM ADD CONSTRAINT FK_RESULT FOREIGN KEY (ID_RESULT) REFERENCES RESULT(ID);
ALTER TABLE BILL_ITEM ADD CONSTRAINT FK_BILL_ITEM FOREIGN KEY (ID_BILL) REFERENCES BILL(ID);
ALTER TABLE PAYMENTS ADD CONSTRAINT FK_USER FOREIGN KEY (ID_USER) REFERENCES USER(ID);
ALTER TABLE SAMPLE ADD CONSTRAINT FK_SAMPLE_TEST_REQUEST FOREIGN KEY (ID_TEST_REQUEST) REFERENCES TEST_REQUEST(ID);
ALTER TABLE SAMPLE ADD CONSTRAINT FK_SAMPLE_TYPE FOREIGN KEY (ID_SAMPLE_TYPE) REFERENCES SAMPLE_TYPE(ID);
ALTER TABLE USER_ROLE ADD CONSTRAINT FK_ROLE FOREIGN KEY (ID_ROLE) REFERENCES ROLE(ID);
ALTER TABLE USER_ROLE ADD CONSTRAINT FK_USER_R FOREIGN KEY (ID_USER) REFERENCES USER(ID);



 